# Port
server:
    port: 8090

# Application Name
spring:
    application:
        name: loan-service

    # DataSource configuration for connecting to H2 in-memory database
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: ''

    # H2 Console configuration for enabling access to H2 database console
    h2:
        console:
            enabled: true

    # JPA configuration for Hibernate
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        show-sql: true