-- Create the Loan table if it doesn't exist
CREATE TABLE IF NOT EXISTS Loan (
    ID BIGINT NOT NULL PRIMARY KEY,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    CREATED_BY VARCHAR(20) NOT NULL,
    UPDATED_AT TIMESTAMP(6),
    UPDATED_BY VARCHAR(20),
    AMOUNT_OUTSTANDING NUMERIC(38, 2) NOT NULL,
    AMOUNT_PAID NUMERIC(38, 2) NOT NULL,
    LOAN_NUMBER BIGINT NOT NULL,
    LOAN_TYPE VARCHAR(100) NOT NULL,
    MOBILE_NUMBER VARCHAR(15) NOT NULL,
    TOTAL_LOAN NUMERIC(38, 2) NOT NULL
    );
